### PR TITLE
do not allow includes in the config by default

### PR DESCRIPTION
**Pull request by vdloo**
reject configs with `include` or `load_module` so the state of the config can not change without going through the reloader.

### CODE REVIEW

**Comment by allardhoeve** [comment]
Ff linken naar knowledge base en uitleggen?

**Comment by vdloo** [comment]
```
app@uaij4r-vdloo-magweb-do:~/nginx$ ls | grep error_output

app@uaij4r-vdloo-magweb-do:~/nginx$ echo 'include test;' >> test.conf 
app@uaij4r-vdloo-magweb-do:~/nginx$ cat nginx_error_output 
nginx: [emerg] open() "/etc/nginx/test" failed (2: No such file or directory) in /etc/nginx/app/test.conf:33
nginx: configuration file /etc/nginx/nginx.conf test failed

app@uaij4r-vdloo-magweb-do:~/nginx$ echo 'include /test;' > test.conf 
app@uaij4r-vdloo-magweb-do:~/nginx$ cat nginx_error_output 
You are not allowed to use include or load_module in the nginx config. See the NGINX dos and don'ts in this article: https://support.hypernode.com/knowledgebase/how-to-use-nginx/

app@uaij4r-vdloo-magweb-do:~/nginx$ echo 'include /etc/nginx/app/test;' > test.conf 
app@uaij4r-vdloo-magweb-do:~/nginx$ cat nginx_error_output 
nginx: [emerg] open() "/etc/nginx/app/test" failed (2: No such file or directory) in /etc/nginx/app/test.conf:1
nginx: configuration file /etc/nginx/nginx.conf test failed
```

```
# Using include or load_module is forbidden unless
# - it is in a comment
# - the include is a relative path but does not start with ..
# - the include is absolute but to the MAIN_CONFIG_DIR
```

**Comment by szepeviktor** [comment]
> # - the include is a relative path but does not start with ..

How about `somedir/../../../../danger` ?

**Comment by vdloo** [comment]
@szepeviktor got that covered now `(?=.*\.\.` thanks

**Pull request merged**
