### PR TITLE
Add arguments to make usage in non-hypernode platforms possible

### PR DESCRIPTION
**Pull request by tdgroot**
I added 3 arguments:
- `--nomagentoconfig` Disables Magento specific configuration placement
- `--nocustomconfig` Disables custom configuration copying from watch dir to /etc/nginx/app
- `--watchdir` Specify directory to watch for changes

This allows me to edit my user nginx config files and reload nginx on change in my own local environment. I don't intend to use this for production, just for my local environment.

Please let me know if you have suggestions and/or improvements!

### CODE REVIEW

**Comment by vdloo** [comment]
Hi @tdgroot! Thanks for the contribution, looks great! Some issues though, in Python it is really not idiomatic to use globals so before I can merge that would have to be changed to threading the variables down to where they are used, like for example:

```python
def main():
    args = parse_nginx_config_reloader_arguments()
    log = get_logger()

    if args.monitor:
        # Track changed files in the nginx config dir and reload on change
        wait_loop(
            logger=log,
            no_magento_config=args.nomagentoconfig,
            no_custom_config=args.nocustomconfig,
            dir_to_watch=args.watchdir
        )
        # should never return
        return 1
    else:
        # Reload the config once
        NginxConfigReloader(
            logger=log,
            no_magento_config=args.nomagentoconfig,
            install_custom_config=args.install_custom_config,
            dir_to_watch=args.watchdir
        ).apply_new_config()
        return 0
```

and then setting the default for watchdir to the previous constant like so:
```python
    parser.add_argument('--watchdir', '-w', help='Set directory to watch', default=DIR_TO_WATCH)
```

Then in the `wait_loop` you can pass down these variables to the NginxConfigReloader like so:
```python
def wait_loop(logger=None, no_magento_config=False, no_custom_config=False, dir_to_watch=DIR_TO_WATCH):
    """Main event loop

    There is an outer loop that checks the availability of the directory to watch.
    As soon as it becomes available, it starts an inotify-monitor that monitors
    configuration changes in an inner event loop. When the monitored directory is
    renamed or removed, the inotify-handler raises an exception to break out of the
    inner loop and we're back here in the outer loop.

    :param obj logger: The logger object
    :param bool no_magento_config: True if we should not watch the /data/web/nginx dir
    :param bool no_custom_config:
    :param str dir_to_watch: The dir to watch
    :return None:
    """
    wm = pyinotify.WatchManager()
    handler = NginxConfigReloader(
        logger=logger, no_magento_config=no_magento_config, no_custom_config=no_custom_config, dir_to_watch=dir_to_watch
    )
```

and then directly use `dir_to_watch` in the rest of that function, for example:
```python
    while True:
        while not os.path.exists(dir_to_watch):
            logger.warning("Configuration dir %s not found, waiting..." % dir_to_watch)
            time.sleep(5)
```

The NginxConfigReloader class could then start with this:
```python
class NginxConfigReloader(pyinotify.ProcessEvent):

    def my_init(self, logger=None, no_magento_config=False, no_custom_config=False, dir_to_watch=DIR_TO_WATCH):
        """Constructor called by ProcessEvent

        :param obj logger: The logger object
        :param bool no_magento_config: True if we should not watch the /data/web/nginx dir
        :param bool no_custom_config:
        :param str dir_to_watch: The dir to watch
        """
        if not logger:
            self.logger = logging
        else:
            self.logger = logger
        self.no_magento_config = no_magento_config
        self.no_custom_config = no_custom_config
        self.dir_to_watch = dir_to_watch
```

and then all the uses of the `DIR_TO_WATCH` constant can be replaced with `self.dir_to_watch`, like for example:
```python
    def check_no_forbidden_config_directives_are_present(self):
        """
        Loop over the :FORBIDDEN_CONFIG_REGEX: to check if nginx config directory contains forbidden configuration
         options
        :return bool:
                        True    if forbidden config directives are present
                        False   if check couldn't find any forbidden config flags
        """
        if os.path.isdir(self.dir_to_watch):
            for rules in FORBIDDEN_CONFIG_REGEX:
                try:
                    check_external_resources = \
                        "[ $(grep -r -P '{}' '{}' | wc -l) -lt 1 ]".format(
                            rules[0], self.dir_to_watch
                        )
                    subprocess.check_output(check_external_resources, shell=True)
                except subprocess.CalledProcessError:
                    error = "Unable to load config: {}".format(rules[1])
                    self.logger.error(error)
                    self.write_error_file(error)
                    return True
            return False
```

and `apply_new_config` could then start like so:
```python
    def apply_new_config(self):
        if self.check_no_forbidden_config_directives_are_present():
            return False

        if not self.no_magento_config:
            try:
                self.install_magento_config()
            except OSError:
                self.logger.error("Installation of magento config failed")
                return False

        if not self.no_custom_config:
            try:
                self.install_new_custom_config_dir()
            except OSError:
                self.logger.error("Installation of custom config failed")
                return False
```
and so on

Also you can run the unit tests with `./runtests.sh` script, currently there are some failing tests:
```python
./runtests.sh -1
....................[2017-10-17 14:04:19,898 pyinotify ERROR]
..........EF.FFF..FF.E.............F..
======================================================================
ERROR: test_that_apply_config_moves_files_to_dest_dir_if_it_doesnt_yet_exist (tests.test_nginx_config_reloader.TestConfigReloader)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vdloo/code/projects/nginx_config_reloader/tests/test_nginx_config_reloader.py", line 61, in test_that_apply_config_moves_files_to_dest_dir_if_it_doesnt_yet_exist
    contents = self._read_file(self._dest('myfile'))
  File "/home/vdloo/code/projects/nginx_config_reloader/tests/test_nginx_config_reloader.py", line 295, in _read_file
    with open(name) as f:
IOError: [Errno 2] No such file or directory: '/tmp/tmp0H0qD9/myfile'
-------------------- >> begin captured logging << --------------------
root: INFO: Reloading nginx config
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_that_apply_new_config_moves_files_to_dest_dir (tests.test_nginx_config_reloader.TestConfigReloader)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vdloo/code/projects/nginx_config_reloader/tests/test_nginx_config_reloader.py", line 51, in test_that_apply_new_config_moves_files_to_dest_dir
    contents = self._read_file(self._dest('myfile'))
  File "/home/vdloo/code/projects/nginx_config_reloader/tests/test_nginx_config_reloader.py", line 295, in _read_file
    with open(name) as f:
IOError: [Errno 2] No such file or directory: '/tmp/tmpzvbl7y/myfile'
-------------------- >> begin captured logging << --------------------
root: INFO: Reloading nginx config
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: test_that_apply_new_config_defaults_to_magento1_config (tests.test_nginx_config_reloader.TestConfigReloader)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vdloo/code/projects/nginx_config_reloader/tests/test_nginx_config_reloader.py", line 72, in test_that_apply_new_config_defaults_to_magento1_config
    self.assertTrue(os.path.islink(self.mag_conf))
AssertionError: False is not true
-------------------- >> begin captured logging << --------------------
root: INFO: Reloading nginx config
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: test_that_apply_new_config_does_not_install_configs_if_magento1_config_doesnt_exist (tests.test_nginx_config_reloader.TestConfigReloader)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vdloo/code/projects/nginx_config_reloader/tests/test_nginx_config_reloader.py", line 83, in test_that_apply_new_config_does_not_install_configs_if_magento1_config_doesnt_exist
    self.assertFalse(ret)
AssertionError: True is not false
-------------------- >> begin captured logging << --------------------
root: INFO: Reloading nginx config
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: test_that_apply_new_config_does_not_install_configs_if_magento2_config_doesnt_exist (tests.test_nginx_config_reloader.TestConfigReloader)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vdloo/code/projects/nginx_config_reloader/tests/test_nginx_config_reloader.py", line 112, in test_that_apply_new_config_does_not_install_configs_if_magento2_config_doesnt_exist
    self.assertFalse(ret)
AssertionError: True is not false
-------------------- >> begin captured logging << --------------------
root: INFO: Reloading nginx config
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: test_that_apply_new_config_doesnt_fail_on_failing_copy (tests.test_nginx_config_reloader.TestConfigReloader)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vdloo/code/projects/nginx_config_reloader/tests/test_nginx_config_reloader.py", line 239, in test_that_apply_new_config_doesnt_fail_on_failing_copy
    self.assertEqual(len(self.test_config.mock_calls), len(nginx_config_reloader.FORBIDDEN_CONFIG_REGEX))
AssertionError: 4 != 3
-------------------- >> begin captured logging << --------------------
root: INFO: Reloading nginx config
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: test_that_apply_new_config_enables_magento1_config_if_customer_sets_flag (tests.test_nginx_config_reloader.TestConfigReloader)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vdloo/code/projects/nginx_config_reloader/tests/test_nginx_config_reloader.py", line 126, in test_that_apply_new_config_enables_magento1_config_if_customer_sets_flag
    self.assertTrue(os.path.islink(self.mag_conf))
AssertionError: False is not true
-------------------- >> begin captured logging << --------------------
root: INFO: Reloading nginx config
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: test_that_apply_new_config_keeps_current_magento_config_if_symlinking_new_config_goes_wrong (tests.test_nginx_config_reloader.TestConfigReloader)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vdloo/code/projects/nginx_config_reloader/tests/test_nginx_config_reloader.py", line 97, in test_that_apply_new_config_keeps_current_magento_config_if_symlinking_new_config_goes_wrong
    self.assertFalse(ret)
AssertionError: True is not false
-------------------- >> begin captured logging << --------------------
root: INFO: Reloading nginx config
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: test_parse_nginx_config_reloader_arguments_adds_options (tests.test_parse_nginx_config_reloader_arguments.TestParseNginxConfigReloaderArguments)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vdloo/code/projects/nginx_config_reloader/tests/test_parse_nginx_config_reloader_arguments.py", line 26, in test_parse_nginx_config_reloader_arguments_adds_options
    self.parser.return_value.add_argument.mock_calls, expected_calls
AssertionError: [call('--monitor', '-m', action='store_true', help='Monitor files on foreground with output'),
 call('--nomagentoconfig', action='store_true', help='Disable Magento configuration'),
 call('--nocustomconfig', action='store_true', help='Disable copying custom configuration'),
 call('--watchdir', '-w', help='Set directory to watch')] != [call('--monitor', '-m', action='store_true', help='Monitor files on foreground with output')]

----------------------------------------------------------------------
Ran 58 tests in 0.189s

FAILED (errors=2, failures=7)
```

**Comment by tdgroot** [comment]
@vdloo thank you for the suggestions. I kind of hoped for feedback like this as it felt kind of quick and dirty. I'll get back to you when it's better and the tests are running!

**Comment by tdgroot** [comment]
@vdloo it's better now:

- Removed hacking of the `DIR_TO_WATCH` constant.
- Added the arguments to `wait_loop()` and `NginxConfigReloader()`.
- Replaced constant `MAGENTO2_FLAG` with a field, because it was relying on `DIR_TO_WATCH`.
- Replaced `DIR_TO_WATCH` usage inside the class with field `dir_to_watch`.

As for the tests:
- Added missing arguments to tests.
- Added 4 tests for cli arguments `--nomagentoconfig` and `--nocustomconfig`.

**Comment by vdloo** [comment]
very nice :+1: I'll fix up some things in the `add-args-to-make-usage-on-non-hyp-platforms-possible` branch but this looks about good to go

**Pull request merged**
